spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: mysecretpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
